language: php

php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" || ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer require phpunit/phpunit "~5.7"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.4" || ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]]; then composer require satooshi/php-coveralls '~1.0'; else composer require satooshi/php-coveralls; fi
  - composer install

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" || ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then vendor/bin/phpunit --version && vendor/bin/phpunit --coverage-clover tmp/clover.xml; else phpunit --version && phpunit --coverage-clover tmp/clover.xml; fi

after_success:
  - php vendor/bin/coveralls -v
